### ISSUE TITLE
INTERNALERROR> AttributeError: CaptureManager instance has no attribute 'suspendcapture'

### ISSUE THREAD

**Issue by 130s** [tgoodlet/pytest-interactive#22]
# Issue

```
$ docker-compose -f docker-compose.yml up
Recreating pctest1 ... done
Attaching to pctest1
pctest1 | ============================= test session starts ==============================
pctest1 | platform linux2 -- Python 2.7.17, pytest-3.3.2, py-1.5.2, pluggy-0.6.0
pctest1 | rootdir: /opt/por/share/p1at/src/p1at/test_mods/sec7, inifile:
pctest1 | plugins: interactive-0.1.4
pctest1 | collected 1 item
pctest1 | INTERNALERROR> Traceback (most recent call last):
pctest1 | INTERNALERROR>   File "/usr/lib/python2.7/dist-packages/_pytest/main.py", line 105, in wrap_session
pctest1 | INTERNALERROR>     session.exitstatus = doit(config, session) or 0
pctest1 | INTERNALERROR>   File "/usr/lib/python2.7/dist-packages/_pytest/main.py", line 142, in _main
pctest1 | INTERNALERROR>     config.hook.pytest_collection(session=session)
pctest1 | INTERNALERROR>   File "/usr/lib/python2.7/dist-packages/pluggy/__init__.py", line 617, in __call__
pctest1 | INTERNALERROR>     return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
pctest1 | INTERNALERROR>   File "/usr/lib/python2.7/dist-packages/pluggy/__init__.py", line 222, in _hookexec
pctest1 | INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
pctest1 | INTERNALERROR>   File "/usr/lib/python2.7/dist-packages/pluggy/__init__.py", line 216, in <lambda>
pctest1 | INTERNALERROR>     firstresult=hook.spec_opts.get('firstresult'),
pctest1 | INTERNALERROR>   File "/usr/lib/python2.7/dist-packages/pluggy/callers.py", line 201, in _multicall
pctest1 | INTERNALERROR>     return outcome.get_result()
pctest1 | INTERNALERROR>   File "/usr/lib/python2.7/dist-packages/pluggy/callers.py", line 77, in get_result
pctest1 | INTERNALERROR>     _reraise(*ex)  # noqa
pctest1 | INTERNALERROR>   File "/usr/lib/python2.7/dist-packages/pluggy/callers.py", line 180, in _multicall
pctest1 | INTERNALERROR>     res = hook_impl.function(*args)
pctest1 | INTERNALERROR>   File "/usr/lib/python2.7/dist-packages/_pytest/main.py", line 152, in pytest_collection
pctest1 | INTERNALERROR>     return session.perform_collect()
pctest1 | INTERNALERROR>   File "/usr/lib/python2.7/dist-packages/_pytest/main.py", line 685, in perform_collect
pctest1 | INTERNALERROR>     config=self.config, items=items)
pctest1 | INTERNALERROR>   File "/usr/lib/python2.7/dist-packages/pluggy/__init__.py", line 617, in __call__
pctest1 | INTERNALERROR>     return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
pctest1 | INTERNALERROR>   File "/usr/lib/python2.7/dist-packages/pluggy/__init__.py", line 222, in _hookexec
pctest1 | INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
pctest1 | INTERNALERROR>   File "/usr/lib/python2.7/dist-packages/pluggy/__init__.py", line 216, in <lambda>
pctest1 | INTERNALERROR>     firstresult=hook.spec_opts.get('firstresult'),
pctest1 | INTERNALERROR>   File "/usr/lib/python2.7/dist-packages/pluggy/callers.py", line 201, in _multicall
pctest1 | INTERNALERROR>     return outcome.get_result()
pctest1 | INTERNALERROR>   File "/usr/lib/python2.7/dist-packages/pluggy/callers.py", line 77, in get_result
pctest1 | INTERNALERROR>     _reraise(*ex)  # noqa
pctest1 | INTERNALERROR>   File "/usr/lib/python2.7/dist-packages/pluggy/callers.py", line 180, in _multicall
pctest1 | INTERNALERROR>     res = hook_impl.function(*args)
pctest1 | INTERNALERROR>   File "/usr/local/lib/python2.7/dist-packages/interactive/plugin.py", line 28, in pytest_collection_modifyitems
pctest1 | INTERNALERROR>     capman.suspendcapture(in_=True)
pctest1 | INTERNALERROR> AttributeError: CaptureManager instance has no attribute 'suspendcapture'
pctest1 | 
pctest1 | ========================= no tests ran in 0.86 seconds =========================
pctest1 exited with code 3
```

# Environment
- Pythons are listed in the output above.
- Ubuntu 16.04

 (yes some are EoL but our production is about to migrate to newer distro and Py3 :/)

Part of my `docker-compose.yml`
```
  command: /bin/bash -c "pytest --interactive -s /test.py"
```

**Comment by Dotrar** [comment]
you are using an older version of the package, installing from git fixes this.
```
pip uninstall pytest-interactive
pip install git+https://github.com/goodboy/pytest-interactive
```
